name: party-dev

services:
  app:
    build: .
    image: party-bot-test
    container_name: party-bot-server-test
    volumes:
      - "./src:/app/src"
      - "./data:/app/data"
    ports:
      - "8080:3000"
    command: ["npm", "run", "dev"]
