name: ${DOCKER_COMPOSE_NAME}

services:
  app:
    build: .
    image: party-bot
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - "./src:/app/src"
      - "./data:/app/data"
      - "./index.ts:/app/index.ts"
    ports:
      - "${HOST_PORT}:3000"
    command: ["/entrypoint.dev.sh"]
