name: ${DOCKER_COMPOSE_NAME}

services:
  app:
    build: .
    image: party-bot
    container_name: ${CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - "./data:/app/data"
    ports:
      - "${HOST_PORT}:3000"
    command: ["/entrypoint.sh"]
